// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/seymourtang/project-layout/internal/data/cache/redis"
	"github.com/seymourtang/project-layout/internal/server/http"
)

// Injectors from wire.go:

func Build() (*Injector, func(), error) {
	serveMux, cleanup := http.New()
	universalClient, cleanup2, err := redis.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	injector := NewInjector(serveMux, universalClient)
	return injector, func() {
		cleanup2()
		cleanup()
	}, nil
}
