// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/seymourtang/project-layout/cmd/app/option"
	"github.com/seymourtang/project-layout/internal/data/cache/redis"
	"github.com/seymourtang/project-layout/internal/data/db"
	redis2 "github.com/seymourtang/project-layout/internal/mq/redis"
	"github.com/seymourtang/project-layout/internal/repository"
	"github.com/seymourtang/project-layout/internal/server/http"
	"github.com/seymourtang/project-layout/internal/task"
)

// Injectors from wire.go:

func Build() (*injector, func(), error) {
	optionOption, err := option.NewCmd()
	if err != nil {
		return nil, nil, err
	}
	v := option.NewMySQLConfig(optionOption)
	gormDB, err := db.New(v)
	if err != nil {
		return nil, nil, err
	}
	studentImpl := repository.NewStudentImpl(gormDB)
	v2 := option.NewRedisConfig(optionOption)
	universalClient, cleanup, err := redis.New(v2)
	if err != nil {
		return nil, nil, err
	}
	httpOption := option.NewHttpConfig(optionOption)
	router := http.NewRouter()
	server := http.New(httpOption, router)
	channelMQ := redis2.NewChannelMQ(universalClient)
	v3 := task.NewGroup(server, channelMQ)
	injectorInjector := NewInjector(studentImpl, universalClient, v3)
	return injectorInjector, func() {
		cleanup()
	}, nil
}
